language: node_js
node_js:
  - "7"

cache:
  yarn: true
  directories:
    - "node_modules"

install:
  - yarn
  - yarn global add codacy-coverage
  
script:
  - yarn build
  
deploy:
  provider: npm
  email: "limaofeng@msn.com"
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true