language: node_js
node_js:
  - "8"

cache:
  yarn: true
  directories:
    - "node_modules"

install:
  - yarn
  - yarn global add codacy-coverage
  
# script:
#   - yarn run test
#   - cat coverage/lcov.info | codacy-coverage
  
deploy:
  provider: npm
  email: "limaofeng@msn.com"
  api_key: $NPM_TOKEN
  skip_cleanup: true
  on:
    tags: true

notifications:
  email: false
  slack:
    rooms:
      - kharak:xDTQ38LSCPeHFSievVaRMEcG #moment
    on_success: change
    on_failure: always